### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by hotice** [tualatrix/vpn-indicator#1]
VPN Indicator doesn't work for me in Ubuntu 11.04 (installed from your PPA). Here's what I get when running it:

Traceback (most recent call last):
  File "/usr/bin/vpn-indicator", line 114, in checkvpn_status
    pynotify.Notification(self._current_config, 'VPN disconnected', 'vpn-indicator').show()
TypeError: Notify.Notification.__init__() argument 1 must be string, not None

**Comment by tualatrix** [comment]
Hi, Thanks for your report. I've fixed this problem and release the new version.

With VPN Indicator, you should make your configs suffixed with "*.ovpn", and it will link the current config as "/etc/openvpn/openvpn.conf", so you should not create a config named with "openvpn.conf".

It is not a generic vpn tools yet, so please follow this rule.
